config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
  end
  get "/login", to: "sessions#new"
  get "/signup", to: "users#new"
  get "/logout", to: "sessions#destroy"

  resources :orders, only: [:create, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :show, :new, :create]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category
  has_many :reviews

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  http_basic_authenticate_with name: ENV['ADMIN_USER'], password: ENV['ADMIN_PASSWORD']

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
      <%= image_tag product.image.thumb, alt: product.name %>
      <h4><%= product.name %></h4>
      <h5>overall rate: <%= number_with_precision(product.reviews.average(:rating), precision: 1) || 'N/A'%> </h5>
    <% end %>
  </header>

    <% if product.quantity == 0 %>
      <aside class="sold_out"> sold out! </aside>
    <% end %>

  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <%= link_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary', method: :put do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
</article>

app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd><%= @product.price %></dd>
          <dt>Overall Rating</dt>
          <dd><%= number_with_precision(@product.reviews.average(:rating), precision: 1)|| 'N/A'%></dd>
        </dl>
      </div>
    </div>


    <% if current_user  %>
      <div class="row">
        <%= form_for [@product, @product.reviews.new] do |form| %>

          <% if form.object.errors.any? %>
            <div class="alert alert-danger">
              <strong>The following errors prevented saving:</strong>
              <ul>
                <% form.object.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :rating %>
            <%= form.select :rating, options_for_select(1..5), class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control' %>
          </div>

          <%= form.submit 'Submit Review', class: 'btn btn-primary' %>
        <% end %>

      </div>
    <% else %>
      <%= link_to "login to creat a review", new_session_path %>
    <% end %>

    <div class="row">

      <h3> Reviews </h2>
      <dl class="dl-horizontal">
      <% @product.reviews.order("created_at desc").each do |review| %>
        <% if review.id %>
          <dt>reviewer:</dt>
          <dd><%= review.user.first_name %></dd>
          <dt>rate:</dt>
          <dd><%= review.rating %></dd>
          <dt>comment:</dt>
          <dd><%= review.description %></dd>
          <dt>date:</dt>
          <dd><%= review.created_at %></dd>

          </ul>
          <% if current_user && current_user.id == review.user.id %>
          <dt></dt>
          <dd><%= link_to "delete", product_review_path(@product, review), :method => :delete, :confirm => "Are you sure?" %></dd>
          <% end %>
        <% end %>
      <% end %>
      </dl>

    </div>

  </article>

</section>